# Generated by Django 5.2 on 2025-08-21 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('DINE_IN', 'Dine In'), ('TAKEAWAY', 'Takeaway'), ('ONLINEDELIVERY', 'OnlineDelivery')], default='DINE_IN', max_length=20)),
                ('quantity', models.IntegerField(blank=True, default=1, null=True)),
                ('CustomerName', models.CharField(blank=True, max_length=100, null=True)),
                ('PhoneNumber', models.IntegerField(blank=True, null=True)),
                ('TotalAmount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Item_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accountapp.itemtable')),
                ('deliveryboy_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accountapp.deliveryboytable')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accountapp.paymenttable')),
                ('table_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accountapp.diningtable')),
                ('waiter_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accountapp.waitertable')),
            ],
        ),
    ]
