# Generated by Django 5.2.4 on 2025-07-28 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managertable',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='managertable',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
