# Generated by Django 5.2.4 on 2025-08-04 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carouseltable',
            name='category',
        ),
        migrations.AddField(
            model_name='carouseltable',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carousel_offers', to='Accountapp.offertable'),
        ),
        migrations.AddField(
            model_name='itemtable',
            name='calories',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offertable',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='carouseltable',
            name='branch',
        ),
        migrations.AlterField(
            model_name='itemtable',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='managertable',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='managertable',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='waitertable',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carouseltable',
            name='branch',
            field=models.ManyToManyField(to='Accountapp.branchtable'),
        ),
    ]
