# Generated by Django 5.2.3 on 2025-07-01 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accountapp.branchtable'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='image',
            field=models.FileField(upload_to='carousel_images/'),
        ),
    ]
