# Generated by Django 5.2 on 2025-08-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouseltable',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
