# Generated by Django 5.2.4 on 2025-07-25 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branchtable',
            name='manager',
        ),
    ]
