# Generated by Django 5.2.4 on 2025-08-25 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0001_initial'),
    ]

    operations = [
    ]
