# Generated by Django 5.2.4 on 2025-08-12 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printertable',
            name='subsubcategories',
        ),
        migrations.AddField(
            model_name='carouseltable',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='printertable',
            name='subcategories',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='printers', to='Accountapp.subcategorytable'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deliveryboytable',
            name='userid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deliveryboy_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='userid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accountapp.profiletable'),
        ),
        migrations.AlterField(
            model_name='profiletable',
            name='loginid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
