# Generated by Django 5.2 on 2025-08-04 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0002_carouseltable'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertable',
            name='deliveryid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='Accountapp.deliveryboytable'),
        ),
    ]
