# Generated by Django 5.2 on 2025-08-01 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0002_alter_ordertable_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemtable',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variant_items', to='Accountapp.itemvarianttable'),
        ),
    ]
