# Generated by Django 5.2 on 2025-08-05 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0002_carouseltable_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarouselTable',
        ),
    ]
