# Generated by Django 5.2 on 2025-08-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0002_offlineorders'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytable',
            name='voice_instruction',
            field=models.FileField(blank=True, null=True, upload_to='delivery_instructions/'),
        ),
    ]
