# Generated by Django 5.2.4 on 2025-08-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0002_remove_printertable_subsubcategories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtable',
            name='available',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
