# Generated by Django 5.2 on 2025-08-02 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0002_add_calories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtable',
            name='calories',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
