# Generated by Django 5.2.4 on 2025-07-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0002_alter_managertable_email_alter_managertable_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitertable',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
