# Generated by Django 5.2.3 on 2025-07-01 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0002_alter_carousel_branch_alter_carousel_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carousel',
            new_name='CarouselTable',
        ),
    ]
