# Generated by Django 5.2.3 on 2025-06-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0002_coupontable_kitchensectiontable_carttable_addon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('KITCHEN', 'Kitchen'), ('WAITER', 'Waiter'), ('DELIVERY', 'Delivery Boy'), ('USER', 'User')], max_length=20, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='logintable',
            name='user_type',
        ),
        migrations.AddField(
            model_name='logintable',
            name='user_roles',
            field=models.ManyToManyField(related_name='users', to='Accountapp.userrole'),
        ),
    ]
