# Generated by Django 5.2.4 on 2025-08-04 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0002_remove_carouseltable_category_carouseltable_offer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offertable',
            name='is_active',
        ),
    ]
