# Generated by Django 5.2.4 on 2025-07-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0002_remove_branchtable_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorytable',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
        migrations.AlterField(
            model_name='categorytable',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
