# Generated by Django 5.2.4 on 2025-08-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0003_remove_offertable_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='offertable',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
