# Generated by Django 5.2.4 on 2025-07-26 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0003_categorytable_image_alter_categorytable_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategorytable',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='subcategory_images/'),
        ),
        migrations.AddField(
            model_name='subsubcategorytable',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='subsubcategory_images/'),
        ),
        migrations.AlterField(
            model_name='subcategorytable',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subsubcategorytable',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
