# Generated by Django 5.2 on 2025-08-04 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0003_ordertable_deliveryid'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryBoyLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_boy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='Accountapp.deliveryboytable')),
            ],
        ),
    ]
