# Generated by Django 5.2 on 2025-08-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0003_deliverytable_voice_instruction'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertable',
            name='voice_instruction',
            field=models.FileField(blank=True, null=True, upload_to='order_voice_instructions/'),
        ),
    ]
