# Generated by Django 5.2.4 on 2025-07-30 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0003_alter_waitertable_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtable',
            name='calories',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
