# Generated by Django 5.2.3 on 2025-07-01 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0003_rename_carousel_carouseltable'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotlightTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='spotlight_images/')),
                ('offer_percentage', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accountapp.branchtable')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accountapp.subcategorytable')),
            ],
        ),
    ]
