# Generated by Django 5.2.3 on 2025-06-27 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0003_userrole_remove_logintable_user_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('place', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('floors', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('managers', models.ManyToManyField(blank=True, related_name='branches_managed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiningTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('table_number', models.CharField(max_length=20)),
                ('seating_capacity', models.IntegerField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dining_tables', to='Accountapp.branchtable')),
            ],
            options={
                'unique_together': {('branch', 'floor', 'table_number')},
            },
        ),
        migrations.CreateModel(
            name='BillTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(max_length=50, unique=True)),
                ('subtotal', models.FloatField(default=0.0)),
                ('tax', models.FloatField(default=0.0)),
                ('discount', models.FloatField(default=0.0)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('payment_method', models.CharField(blank=True, max_length=20, null=True)),
                ('paid_at', models.CharField(blank=True, max_length=100, null=True)),
                ('total_amount', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='Accountapp.ordertable')),
                ('waiter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills_generated', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='Accountapp.branchtable')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='Accountapp.diningtable')),
            ],
        ),
        migrations.CreateModel(
            name='FloorTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_number', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='no_of_floors', to='Accountapp.branchtable')),
            ],
            options={
                'ordering': ['branch', 'floor_number'],
                'unique_together': {('branch', 'floor_number')},
            },
        ),
    ]
