# Generated by Django 5.2.4 on 2025-08-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryboytable',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
