# Generated by Django 5.2 on 2025-08-05 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0003_delete_carouseltable'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='carousel_images/')),
                ('offer_percentage', models.FloatField(blank=True, default=0.0, null=True)),
                ('startdate', models.DateTimeField(blank=True, null=True)),
                ('enddate', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ManyToManyField(to='Accountapp.branchtable')),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carousel_offers', to='Accountapp.offertable')),
            ],
        ),
    ]
