# Generated by Django 5.2.4 on 2025-07-30 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0004_itemtable_calories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtable',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
