# Generated by Django 5.2.3 on 2025-07-01 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0004_spotlighttable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotlighttable',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accountapp.subcategorytable'),
        ),
    ]
