# Generated by Django 5.2 on 2025-08-21 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0004_ordertable_voice_instruction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverytable',
            name='voice_instruction',
        ),
    ]
