# Generated by Django 5.2 on 2025-08-02 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0004_add_offer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carouseltable',
            name='offer_id',
        ),
    ]
