# Generated by Django 5.2.4 on 2025-08-28 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0004_deliveryboytable_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carttable',
            name='addon',
        ),
        migrations.AddField(
            model_name='carttable',
            name='addon',
            field=models.ManyToManyField(blank=True, null=True, related_name='cart_addons', to='Accountapp.addontable'),
        ),
    ]
