# Generated by Django 5.2.3 on 2025-07-28 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0002_auto_20250725_1200'),
        ('Accountapp', '0004_subcategorytable_image_subsubcategorytable_image_and_more'),
    ]

    operations = [
    ]
