# Generated by Django 5.2.3 on 2025-06-28 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0004_branchtable_diningtable_billtable_floortable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitchentable',
            name='section',
        ),
        migrations.RemoveField(
            model_name='kitchentable',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='addresstable',
            name='address_line1',
        ),
        migrations.RemoveField(
            model_name='addresstable',
            name='address_line2',
        ),
        migrations.RemoveField(
            model_name='billtable',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='categorytable',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='itemtable',
            name='type',
        ),
        migrations.RemoveField(
            model_name='subcategorytable',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='addresstable',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemtable',
            name='is_veg',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='SubSubCategoryTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsubcategories', to='Accountapp.subcategorytable')),
            ],
        ),
        migrations.CreateModel(
            name='PrinterTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printers', to='Accountapp.branchtable')),
                ('subsubcategories', models.ManyToManyField(blank=True, related_name='category', to='Accountapp.subsubcategorytable')),
            ],
        ),
        migrations.AddField(
            model_name='itemtable',
            name='subsubcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='Accountapp.subsubcategorytable'),
        ),
        migrations.DeleteModel(
            name='KitchenSectionTable',
        ),
        migrations.DeleteModel(
            name='KitchenTable',
        ),
    ]
