# Generated by Django 5.2 on 2025-08-06 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0004_carouseltable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiletable',
            name='loginid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
