# Generated by Django 5.2.3 on 2025-07-01 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0005_alter_spotlighttable_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemVariantTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name='branchtable',
            old_name='managers',
            new_name='manager',
        ),
        migrations.RenameField(
            model_name='itemtable',
            old_name='quantity',
            new_name='inventory',
        ),
        migrations.AddField(
            model_name='branchtable',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='managertable',
            name='email',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='waitertable',
            name='email',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='itemtable',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accountapp.itemvarianttable'),
        ),
    ]
