# Generated by Django 5.2.4 on 2025-08-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0005_credituser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offlineorders',
            name='Item_id',
        ),
        migrations.AddField(
            model_name='offlineorders',
            name='Item_id',
            field=models.ManyToManyField(blank=True, to='Accountapp.itemtable'),
        ),
    ]
