# Generated by Django 5.2.4 on 2025-08-28 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0005_remove_carttable_addon_carttable_addon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carttable',
            name='addon',
            field=models.ManyToManyField(blank=True, related_name='cart_addons', to='Accountapp.addontable'),
        ),
    ]
