# Generated by Django 5.2 on 2025-08-06 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0005_alter_profiletable_loginid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryboytable',
            name='userid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deliveryboy_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
