# Generated by Django 5.2 on 2025-08-25 04:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0005_remove_deliverytable_voice_instruction'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='offlineorders',
            old_name='CustomerName',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='offlineorders',
            old_name='deliveryboy_id',
            new_name='deliveryboy',
        ),
        migrations.RenameField(
            model_name='offlineorders',
            old_name='table_id',
            new_name='table',
        ),
        migrations.RenameField(
            model_name='offlineorders',
            old_name='TotalAmount',
            new_name='total_amount',
        ),
        migrations.RenameField(
            model_name='offlineorders',
            old_name='waiter_id',
            new_name='waiter',
        ),
        migrations.RemoveField(
            model_name='offlineorders',
            name='Item_id',
        ),
        migrations.RemoveField(
            model_name='offlineorders',
            name='PhoneNumber',
        ),
        migrations.RemoveField(
            model_name='offlineorders',
            name='quantity',
        ),
        migrations.AddField(
            model_name='offlineorders',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offlineorders',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='offlineorders',
            name='order_type',
            field=models.CharField(choices=[('DINE_IN', 'Dine In'), ('TAKEAWAY', 'Takeaway'), ('ONLINEDELIVERY', 'Online Delivery')], default='DINE_IN', max_length=20),
        ),
        migrations.CreateModel(
            name='OfflineOrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accountapp.itemtable')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='Accountapp.offlineorders')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accountapp.itemvarianttable')),
            ],
        ),
        migrations.DeleteModel(
            name='UserFeedbackTable',
        ),
    ]
