# Generated by Django 5.2.4 on 2025-08-01 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0005_alter_itemtable_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carouseltable',
            name='category',
        ),
        migrations.AddField(
            model_name='carouseltable',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carousel_offers', to='Accountapp.offertable'),
        ),
        migrations.RemoveField(
            model_name='carouseltable',
            name='branch',
        ),
        migrations.AddField(
            model_name='carouseltable',
            name='branch',
            field=models.ManyToManyField(blank=True, null=True, to='Accountapp.branchtable'),
        ),
    ]
