# Generated by Django 5.2.4 on 2025-08-01 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0006_remove_carouseltable_category_carouseltable_offer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouseltable',
            name='branch',
            field=models.ManyToManyField(to='Accountapp.branchtable'),
        ),
    ]
