# Generated by Django 5.2.3 on 2025-07-01 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0006_itemvarianttable_rename_managers_branchtable_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryboytable',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accountapp.branchtable'),
        ),
        migrations.AddField(
            model_name='deliveryboytable',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliveryboytable',
            name='license',
            field=models.FileField(blank=True, null=True, upload_to='deliveryboy_licenses/'),
        ),
    ]
