# Generated by Django 5.2.4 on 2025-08-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0006_alter_carttable_addon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carttable',
            name='addon',
            field=models.ManyToManyField(blank=True, to='Accountapp.addontable'),
        ),
    ]
