# Generated by Django 5.2 on 2025-08-07 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0006_alter_deliveryboytable_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertable',
            name='userid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accountapp.profiletable'),
        ),
    ]
