# Generated by Django 5.2.3 on 2025-07-02 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0007_deliveryboytable_branch_deliveryboytable_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchtable',
            name='manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_roles__role': 'MANAGER'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
