# Generated by Django 5.2 on 2025-09-09 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0007_userfeedbacktable'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlineorders',
            name='credit_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accountapp.credituser'),
        ),
        migrations.AlterField(
            model_name='offlineorders',
            name='payment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
