# Generated by Django 5.2 on 2025-08-12 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0007_alter_ordertable_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printertable',
            name='subsubcategories',
        ),
        migrations.AddField(
            model_name='printertable',
            name='subcategories',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='printers', to='Accountapp.subcategorytable'),
            preserve_default=False,
        ),
    ]
