# Generated by Django 5.2.4 on 2025-09-09 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0007_alter_carttable_addon'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlineorders',
            name='credit_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accountapp.credituser'),
        ),
    ]
