# Generated by Django 5.2.4 on 2025-08-22 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0007_rename_customername_offlineorders_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlineorders',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
