# Generated by Django 5.2 on 2025-08-12 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0008_remove_printertable_subsubcategories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeedbackTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('feedback', models.TextField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_boy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accountapp.deliveryboytable')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accountapp.ordertable')),
            ],
        ),
    ]
