# Generated by Django 5.2.4 on 2025-09-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0008_offlineorders_credit_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offlineorders',
            name='payment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
