# Generated by Django 5.2.4 on 2025-08-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0008_offlineorders_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemtable',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
