# Generated by Django 5.2 on 2025-08-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0009_userfeedbacktable'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtable',
            name='available',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
