# Generated by Django 5.2.4 on 2025-08-22 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0009_orderitemtable_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitemtable',
            name='status',
        ),
    ]
