# Generated by Django 5.2.3 on 2025-07-02 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0009_carouseltable_enddate_carouseltable_startdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('ml', 'Malayalam'), ('hi', 'Hindi'), ('ar', 'Arabic')], max_length=10)),
                ('audio_file', models.FileField(upload_to='voice_descriptions/')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_descriptions', to='Accountapp.itemtable')),
            ],
        ),
    ]
