# Generated by Django 5.2.4 on 2025-09-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0009_alter_offlineorders_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertable',
            name='orderstatus',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('DELIVERED', 'Delivered'), ('PICKED', 'Picked')], default='PENDING', max_length=50),
        ),
    ]
