# Generated by Django 5.2.4 on 2025-08-25 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0010_remove_orderitemtable_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credituser',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
