# Generated by Django 5.2.3 on 2025-07-02 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0010_voicedescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemtable',
            name='voice_description',
        ),
    ]
