# Generated by Django 5.2.3 on 2025-07-02 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0012_rename_voicedescription_voicedescriptiontable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemtable',
            name='variant',
        ),
        migrations.AddField(
            model_name='itemvarianttable',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='Accountapp.itemtable'),
        ),
    ]
