# Generated by Django 5.2.3 on 2025-07-04 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0013_remove_itemtable_variant_itemvarianttable_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='addontable',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, max_length=20, null=True),
        ),
    ]
