# Generated by Django 5.2.3 on 2025-07-04 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0014_addontable_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtable',
            name='newest',
            field=models.BooleanField(default=True),
        ),
    ]
