# Generated by Django 5.2.3 on 2025-07-04 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0015_alter_itemtable_newest'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtable',
            name='preparation_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='ItemImageTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='item_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Accountapp.itemtable')),
            ],
        ),
    ]
