# Generated by Django 5.2.3 on 2025-07-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0016_itemtable_preparation_time_itemimagetable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemtable',
            name='image',
        ),
        migrations.AlterField(
            model_name='itemimagetable',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='item_images/'),
        ),
    ]
