# Generated by Django 5.2.3 on 2025-07-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0017_remove_itemtable_image_alter_itemimagetable_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchtable',
            name='fssai_lic_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='branchtable',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='branch_image/'),
        ),
    ]
