# Generated by Django 5.2.3 on 2025-07-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0018_branchtable_fssai_lic_no_branchtable_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtable',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='items', to='Accountapp.branchtable'),
        ),
    ]
