# Generated by Django 5.2.4 on 2025-07-12 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0019_itemtable_branches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carttable',
            name='addon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_addons', to='Accountapp.addontable'),
        ),
    ]
