# Generated by Django 5.2.3 on 2025-07-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0019_itemtable_branches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addontable',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
