# Generated by Django 5.2.4 on 2025-07-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0020_alter_carttable_addon'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiletable',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
