# Generated by Django 5.2.4 on 2025-07-16 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0020_alter_addontable_quantity'),
        ('Accountapp', '0021_profiletable_email'),
    ]

    operations = [
    ]
