# Generated by Django 5.2.4 on 2025-07-16 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0021_profiletable_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresstable',
            name='orderid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='Accountapp.ordertable'),
        ),
        migrations.AddField(
            model_name='deliverytable',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='Accountapp.addresstable'),
        ),
        migrations.AddField(
            model_name='deliverytable',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='Accountapp.ordertable'),
        ),
        migrations.AddField(
            model_name='ordertable',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='Accountapp.branchtable'),
        ),
        migrations.AddField(
            model_name='profiletable',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliverie', to='Accountapp.addresstable'),
        ),
        migrations.AlterField(
            model_name='addresstable',
            name='address',
            field=models.CharField(blank=True, max_length=455, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryboytable',
            name='name',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='deliverytable',
            name='instruction',
            field=models.CharField(blank=True, max_length=450, null=True),
        ),
        migrations.AlterField(
            model_name='deliverytable',
            name='name',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='orderitemtable',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='Accountapp.ordertable'),
        ),
    ]
