# Generated by Django 5.2.4 on 2025-07-23 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0023_remove_addresstable_userid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addresstable',
            name='orderid',
        ),
    ]
